services:
  dict:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6231:6231"
    entrypoint: ["./run_dict.sh" ]
    command: [ "6231" ]
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "80:8000"
    entrypoint: [ "./run_flask.sh" ]
    environment:
      DICT_URL: http://dict:6231
    depends_on:
      - dict
